### ISSUE TITLE
Failed to get the default branch when the default branch is `main`(TagVersionReleaseWorker::getDefaultBranch)

### ISSUE THREAD

**Issue by guanguans** [symplify/monorepo-builder#52]
![58101692169780_ pic](https://github.com/symplify/monorepo-builder/assets/22309277/270cbea3-9641-4b75-acaf-49bf14462b92)
![58111692169811_ pic](https://github.com/symplify/monorepo-builder/assets/22309277/a9f49e9a-ca92-4591-81a7-4b628d577c0f)

**Comment by kayw-geek** [comment]
This may be because your remote repository `origin` has not yet defined the default branch.

Run `git remote show origin` to check your remote repository. In the "HEAD branch" line, you should see the name of the default branch. If you can't see it, you may need to manually set the remote repository's default branch.

**Comment by kayw-geek** [comment]
<img width="793" alt="image" src="https://github.com/symplify/monorepo-builder/assets/29700073/ae375e1c-134f-493c-bd9a-f8e8b6fa63a4">

**Comment by guanguans** [comment]
It's okay to re cloned, thank you.
